export declare function toUtcTime(dt: Date): Date;
export declare function nowToInt(): number;
export declare function nowToNum(): number;
export declare function nowToDay(): number;
export declare function dateToNum(dt: Date): number;
export declare function numToDate(num: number): Date;
export declare function dateToInt(dt: Date): number;
export declare function intToDate(num: number): Date;
export declare function dayToInt(dt: Date): number;
export declare function intToDay(num: number): Date;
export declare function toInt(n: number): number;
export declare function formatTimeSpan(secs: number): string;
export declare function IsTheSameDay(date1: Date, date2: Date): boolean;
