import { AppBarTheme } from 'react-toolbox/lib/app_bar/AppBar';
import { AutocompleteTheme } from 'react-toolbox/lib/autocomplete/Autocomplete';
import { AvatarTheme } from 'react-toolbox/lib/avatar/Avatar';
import { ButtonTheme } from 'react-toolbox/lib/button/Button';
import { IconButtonTheme } from 'react-toolbox/lib/button/IconButton';
import { BrowseButtonTheme } from 'react-toolbox/lib/button/BrowseButton';
import { CardTheme, CardThemeAll } from 'react-toolbox/lib/card/Card';
import { CardTitleTheme } from 'react-toolbox/lib/card/CardTitle';
import { CardMediaTheme } from 'react-toolbox/lib/card/CardMedia';
import { CardTextTheme } from 'react-toolbox/lib/card/CardText';
import { CardActionsTheme } from 'react-toolbox/lib/card/CardActions';
import { CheckboxTheme } from 'react-toolbox/lib/checkbox/Checkbox';
import { ChipTheme } from 'react-toolbox/lib/chip/Chip';
import { DatePickerTheme } from 'react-toolbox/lib/date_picker/DatePicker';
import { DialogTheme } from 'react-toolbox/lib/dialog/Dialog';
import { DrawerTheme } from 'react-toolbox/lib/drawer/Drawer';
import { DropdownTheme } from 'react-toolbox/lib/dropdown/Dropdown';
import { InputTheme } from 'react-toolbox/lib/input/Input';
import { LayoutTheme, LayoutThemeAll } from 'react-toolbox/lib/layout/Layout';
import { OverlayTheme } from 'react-toolbox/lib/overlay/Overlay';
import { PanelTheme } from 'react-toolbox/lib/layout/Panel';
import { NavDrawerTheme } from 'react-toolbox/lib/layout/NavDrawer';
import { SidebarTheme } from 'react-toolbox/lib/layout/Sidebar';
import { LinkTheme } from 'react-toolbox/lib/link/Link';
import { ListTheme, ListThemeAll } from 'react-toolbox/lib/list/List';
import { ListCheckboxTheme } from 'react-toolbox/lib/list/ListCheckbox';
import { ListItemTheme } from 'react-toolbox/lib/list/ListItem';
import { ListDividerTheme } from 'react-toolbox/lib/list/ListDivider';
import { ListSubHeaderTheme } from 'react-toolbox/lib/list/ListSubHeader';
import { MenuTheme, MenuThemeAll } from 'react-toolbox/lib/menu/Menu';
import { MenuDividerTheme } from 'react-toolbox/lib/menu/MenuDivider';
import { MenuItemTheme } from 'react-toolbox/lib/menu/MenuItem';
import { IconMenuTheme } from 'react-toolbox/lib/menu/IconMenu';
import { NavigationTheme } from 'react-toolbox/lib/navigation/Navigation';
import { ProgressBarTheme } from 'react-toolbox/lib/progress_bar/ProgressBar';
import { RadioButtonTheme } from 'react-toolbox/lib/radio/RadioButton';
import { RippleTheme } from 'react-toolbox/lib/ripple/Ripple';
import { SliderTheme } from 'react-toolbox/lib/slider/Slider';
import { SnackbarTheme } from 'react-toolbox/lib/snackbar/Snackbar';
import { SwitchTheme } from 'react-toolbox/lib/switch/Switch';
import { TableTheme } from 'react-toolbox/lib/table/Table';
import { TabsTheme, TabsThemeAll } from 'react-toolbox/lib/tabs/Tabs';
import { TabTheme } from 'react-toolbox/lib/tabs/Tab';
import { TimePickerTheme } from 'react-toolbox/lib/time_picker/TimePicker';
import { TooltipTheme } from 'react-toolbox/lib/tooltip/Tooltip';
export declare type TTheme = {
    RTAppBar: AppBarTheme;
    RTAutocomplete: AutocompleteTheme;
    RTAvatar: AvatarTheme;
    RTButton: ButtonTheme;
    RTIconButton: IconButtonTheme;
    RTBrowseButton: BrowseButtonTheme;
    RTCardAll: CardThemeAll;
    RTCard: CardTheme;
    RTCardTitle: CardTitleTheme;
    RTCardMedia: CardMediaTheme;
    RTCardText: CardTextTheme;
    RTCardActions: CardActionsTheme;
    RTCheckbox: CheckboxTheme;
    RTChip: ChipTheme;
    RTDatePicker: DatePickerTheme;
    RTDialog: DialogTheme;
    RTDrawer: DrawerTheme;
    RTDropdown: DropdownTheme;
    RTInput: InputTheme;
    RTLayoutAll: LayoutThemeAll;
    RTLayout: LayoutTheme;
    RTOverlay: OverlayTheme;
    RTPanel: PanelTheme;
    RTNavDrawer: NavDrawerTheme;
    RTRadio: RadioButtonTheme;
    RTSidebar: SidebarTheme;
    RTLink: LinkTheme;
    RTListAll: ListThemeAll;
    RTList: ListTheme;
    RTListCheckbox: ListCheckboxTheme;
    RTListItem: ListItemTheme;
    RTListDivider: ListDividerTheme;
    RTListSubHeader: ListSubHeaderTheme;
    RTMenuAll: MenuThemeAll;
    RTMenu: MenuTheme;
    RTMenuDivider: MenuDividerTheme;
    RTMenuItem: MenuItemTheme;
    RTIconMenu: IconMenuTheme;
    RTNavigation: NavigationTheme;
    RTProgressBar: ProgressBarTheme;
    RTRipple: RippleTheme;
    RTSlider: SliderTheme;
    RTSnackbar: SnackbarTheme;
    RTSwitch: SwitchTheme;
    RTTable: TableTheme;
    RTTabsAll: TabsThemeAll;
    RTTabs: TabsTheme;
    RTTab: TabTheme;
    RTTimePicker: TimePickerTheme;
    RTTooltip: TooltipTheme;
};
declare const theme: TTheme;
export default theme;
